# -*- coding: utf-8 -*-
"""УПИИС

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_H56XSwb8haPNZVj1wSeucJi05f2cmVz

Лабораторная работа 1 (Обязательная)Файл
Рублёв В. С. ББМО-02-23
"""

import random
import string

def generate_random_email():
# Генерация случайного имени пользователя
    name_length = random.randint(5, 10)
    name = ''.join(random.choices(string.ascii_lowercase, k=name_length))

# Генерация случайного домена
    domain_length = random.randint(5, 10)
    domain = ''.join(random.choices(string.ascii_lowercase, k=domain_length))

# Генерация случайной локальной части
    local_length = random.randint(2, 4)
    local = ''.join(random.choices(string.ascii_lowercase, k=local_length))

# Сборка email адреса
    email = f"{name}@{domain}.{local}"

    return email

# Пример использования функции
random_email = generate_random_email()
print(random_email)

